### PR TITLE
fix routing_table, it should be int as per the schema

### PR DESCRIPTION
**Pull request by gsimko**

### CODE REVIEW

**Comment by OJFord** [comment]
Does this stem from some kind of issue? The schema description does say 'or "off"', which (though I've forgotten context and would need to look into it again) suggests to me this was deliberate, that it's either an int identifier or the string 'off', and therefore does need to be string?

**Comment by gsimko** [comment]
I've already forgotten the details but the code was failing for sure.
I was referring to the schema in your code:
```
"routing_table": {
  Description: "Controls the routing table (or \"off\") to which routes are added. (`wg-quick`/apps only.)",
  Type:        schema.TypeInt,
  Optional:    true,
},
```

So maybe just updating the type to schema.TypeString would work fine?

**Comment by OJFord** [comment]
Yeah, so was I - that `(or \"off\")` - no worries, I'll have a look later.

**Comment by OJFord** [comment]
Thanks for bringing that to my attention @gsimko - though correct fix seems to change the schema, since the table could be for example `"default"`. I've released v0.3.0 with that fix.

**Pull request closed without merging**
