### PR TITLE
Fix #17: use TypeList instead of TypeSet for pre/post scripts & allow…

### LINKED ISSUE #17: Shuffled lines in Pre/Post scripts
I wrote:
```
data wireguard_config_document server_peer {
  private_key = wireguard_asymmetric_key.server_peer.private_key
  addresses   = ["<...>"]
  listen_port = 51820
  post_up     = [
    # masquerading
    "iptables -t nat -N ${local.wg_chain_prefix}POSTROUTING",
    "iptables -t nat -I POSTROUTING -j ${local.wg_chain_prefix}POSTROUTING",
    "iptables -t nat -A ${local.wg_chain_prefix}POSTROUTING -s ${local.wg_cidr} ! -o %i -j MASQUERADE",
    # firewall
    "iptables -N ${local.wg_chain_prefix}INPUT",
    "iptables -I INPUT -j ${local.wg_chain_prefix}INPUT",
    "iptables -A ${local.wg_chain_prefix}INPUT -i %i -m state --state ESTABLISHED,RELATED -j ACCEPT",
    "iptables -N ${local.wg_chain_prefix}FORWARD",
    "iptables -I FORWARD -j ${local.wg_chain_prefix}FORWARD",
    "iptables -A ${local.wg_chain_prefix}FORWARD -o %i -m state --state ESTABLISHED,RELATED -j ACCEPT",
  ]
  pre_down    = [
    # firewall
    "iptables -D FORWARD -j ${local.wg_chain_prefix}FORWARD",
    "iptables -X ${local.wg_chain_prefix}FORWARD",
    "iptables -D INPUT -j ${local.wg_chain_prefix}INPUT",
    "iptables -X ${local.wg_chain_prefix}INPUT",
    # masquerading
    "iptables -D INPUT -j ${local.wg_chain_prefix}POSTROUTING",
    "iptables -X ${local.wg_chain_prefix}POSTROUTING",
  ]
  <...>
}
```
And I have got result:
```
[Interface]
PrivateKey = <...>
ListenPort = 51820
Address = <...>
PostUp = iptables -I INPUT -j wg_ab0a9bee_chain_INPUT
PostUp = iptables -t nat -I POSTROUTING -j wg_ab0a9bee_chain_POSTROUTING
PostUp = iptables -N wg_ab0a9bee_chain_FORWARD
PostUp = iptables -N wg_ab0a9bee_chain_INPUT
PostUp = iptables -A wg_ab0a9bee_chain_FORWARD -o wg_ab0a9bee_srv -m state --state ESTABLISHED,RELATED -j ACCEPT
PostUp = iptables -t nat -A wg_ab0a9bee_chain_POSTROUTING -s 192.168.250.0/24 ! -o %i -j MASQUERADE
PostUp = iptables -t nat -N wg_ab0a9bee_chain_POSTROUTING
PostUp = iptables -I FORWARD -j wg_ab0a9bee_chain_FORWARD
PostUp = iptables -A wg_ab0a9bee_chain_INPUT -i %i -m state --state ESTABLISHED,RELATED -j ACCEPT
PreDown = iptables -D INPUT -j wg_ab0a9bee_chain_POSTROUTING
PreDown = iptables -X wg_ab0a9bee_chain_FORWARD
PreDown = iptables -X wg_ab0a9bee_chain_POSTROUTING
PreDown = iptables -D FORWARD -j wg_ab0a9bee_chain_FORWARD
PreDown = iptables -X wg_ab0a9bee_chain_INPUT
PreDown = iptables -D INPUT -j wg_ab0a9bee_chain_INPUT
<...>
```
It produces the error:
```
[#] ip link add wg_ab0a9bee_srv type wireguard
[#] wg setconf wg_ab0a9bee_srv /dev/fd/63
[#] ip -4 address add 192.168.250.1/24 dev wg_ab0a9bee_srv
[#] ip link set mtu 8921 up dev wg_ab0a9bee_srv
[#] iptables -I INPUT -j wg_ab0a9bee_chain_INPUT
iptables v1.8.4 (legacy): Couldn't load target `wg_ab0a9bee_chain_INPUT':No such file or directory
Try `iptables -h' or 'iptables --help' for more information.
[#] ip link delete dev wg_ab0a9bee_srv
```
Wireguard documentation [says](https://manpages.debian.org/bullseye/wireguard-tools/wg-quick.8.en.html#CONFIGURATION):

> PreUp, PostUp, PreDown, PostDown — script snippets which will be executed by [bash(1)](https://manpages.debian.org/bullseye/bash/bash.1.en.html) before/after setting up/tearing down the interface, most commonly used to configure custom DNS options or firewall rules. The special string `%i' is expanded to INTERFACE. Each one may be specified multiple times, in which case the commands **are executed in order**.

So Pre/Post scripts should not change its order.

### PR DESCRIPTION
**Pull request by sprat**
Fix #17: use TypeList instead of TypeSet for pre/post scripts & allowed_ips

### CODE REVIEW

**Comment by sprat** [comment]
Note: I've not tested the changes, I don't know how to do that.

**Comment by sprat** [comment]
I've fixed the documentation, the CI should be green now

**Comment by sprat** [comment]
@OJFord did you had time to review & test this pull request?

**Comment by OJFord** [comment]
Gah sorry, I will do. Let me just merge, seems fine, I'll just double-check before I tag next release.

**Comment by sprat** [comment]
Thanks!

**Pull request merged**
